from __future__ import annotations

from bqskit.ir.gates.cnot import CNOTGate
from bqskit.ir.gates.cz import CZGate
from bqskit.ir.gates.fixedparam import SemiFixedParameterGate
from bqskit.ir.gates.fixedunitary import FixedUnitaryGate
from bqskit.ir.gates.identity import IdentityGate
from bqskit.ir.gates.iswap import ISWAPGate
from bqskit.ir.gates.rx import RXGate
from bqskit.ir.gates.ry import RYGate
from bqskit.ir.gates.rz import RZGate
from bqskit.ir.gates.sqrtcnot import SQRTCNOTGate
from bqskit.ir.gates.u1 import U1Gate
from bqskit.ir.gates.u2 import U2Gate
from bqskit.ir.gates.u3 import U3Gate
from bqskit.ir.gates.variableunitary import VariableUnitaryGate
from bqskit.ir.gates.x import XGate
from bqskit.ir.gates.xx import XXGate
from bqskit.ir.gates.y import YGate
from bqskit.ir.gates.z import ZGate
