ci:
    skip: [mypy]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
        exclude: 'bqskit/ext/rigetti.py'
    -   id: name-tests-test
        args: [--django]
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: check-added-large-files
        args: ['--maxkb=8192']
    -   id: fix-byte-order-marker
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.16.1
#     hooks:
#     -   id: ruff-check
#         args: [--fix]
#     -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.0.0
    hooks:
    - id: mypy
      exclude: tests/qis/test_pauli.py
      additional_dependencies: ["numpy>=1.21"]
