"""This module tests the RYYGate class."""
from __future__ import annotations

import numpy as np

from bqskit.ir.circuit import Circuit
from bqskit.ir.gates import RYYGate
from bqskit.ir.gates import YYGate
from bqskit.ir.gates.circuitgate import CircuitGate
from bqskit.ir.lang.qasm2 import OPENQASM2Language


def test_get_unitary() -> None:
    g = RYYGate()
    u = YYGate().get_unitary()
    assert g.get_unitary([np.pi / 2]).get_distance_from(u) < 1e-7


def test_ryy_qasm_write_includes_definition() -> None:
    c = Circuit(2)
    c.append_gate(RYYGate(), (0, 1), [0.1])
    qasm = OPENQASM2Language().encode(c)
    assert 'gate ryy(param0) q0, q1 {' in qasm
    assert 'ryy(0.1) q[0], q[1];' in qasm


def test_ryy_qasm_read_without_definition() -> None:
    qasm = (
        'OPENQASM 2.0;\n'
        'include "qelib1.inc";\n'
        'qreg q[2];\n'
        'ryy(0.1) q[0], q[1];\n'
    )
    circuit = OPENQASM2Language().decode(qasm)
    assert circuit[0, 0].gate == RYYGate()
    assert circuit.get_unitary() == RYYGate().get_unitary([0.1])


def test_ryy_qasm_read_with_definition_produces_circuit_gate() -> None:
    # QASM as generated by Qiskit
    qasm = (
        'OPENQASM 2.0;\n'
        'include "qelib1.inc";\n'
        'gate ryy(param0) q0,q1 {'
        ' rx(pi/2) q0; rx(pi/2) q1;'
        ' cx q0,q1; rz(param0) q1; cx q0,q1;'
        ' rx(-pi/2) q0; rx(-pi/2) q1; }\n'
        'qreg q[2];\n'
        'ryy(0.1) q[0], q[1];\n'
    )
    circuit = OPENQASM2Language().decode(qasm)
    assert isinstance(circuit[0, 0].gate, CircuitGate)
    assert circuit.get_unitary() == RYYGate().get_unitary([0.1])


def test_ryy_qasm_roundtrip() -> None:
    c = Circuit(2)
    c.append_gate(RYYGate(), (0, 1), [0.1])
    qasm = OPENQASM2Language().encode(c)
    decoded = OPENQASM2Language().decode(qasm)
    assert decoded.get_unitary() == c.get_unitary()
