# Runs slow tests every night
name: nightly tests

on:
  schedule:
    - cron: "21 2 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v9
      with:
        python-version: '3.14'

    - name: Install BQSKit and test dependencies
      run: uv sync --locked --no-default-groups --group test

    - name: Run tests
      env:
        NUMBER_RANDOM_CIRCUITS: 100
      # runs all tests
      run: uv run pytest -m "slow or not slow"

    - name: Run notebooks with nbval
      run: uv run pytest --nbval-lax examples/tutorials/
