name: tests

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [macOS-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install BQSKit and test dependencies
      env:
        SYSTEM_VERSION_COMPAT: 0
      run: uv sync --locked --no-default-groups --group test

    - name: Run tests
      env:
        NUMBER_RANDOM_CIRCUITS: 100
      run: uv run pytest

    - name: Run notebooks with nbval
      run: uv run pytest --nbval-lax examples/tutorials/
